### PR TITLE
Optimization of controller methods

### LINKED ISSUE #320: Optimization of controller methods
Some controller methods have code snippets that can be improved, such as repeating code.
This should be optimized to avoid future problems and facilitate maintainability of the code.

### LINKED ISSUE #336: Bug when exporting graph not written in graph6
When trying to perform an export all through the tree, of a graph that is not written in .g6 the software tries to perform export. The `get_graph_from_tree` function in `controller.py` must be updated and only run in .json, .g6 and .txt formats.

### PR DESCRIPTION
**Pull request by fsoupimenta**
Closes #320 
Closes #336

### CODE REVIEW

**Review by atilaajones — DISMISSED** [review]

**Comment by fsoupimenta** [comment]
> Could you also remove these problems? Would be possible? image

Yes, it's possible. Thanks for pointing out this problem, I had forgotten about it. I will work on the correction

**Comment by atilaajones** [comment]
Please do #336, too.

**Comment by atilaajones** [comment]
Please remove the Change File button temporarily (#216), don't close this issue.

**Comment by fsoupimenta** [comment]
> Please do #336, too.

Done! This PR will close this issue too.

**Review by atilaajones — APPROVED** [review]

**Pull request merged**
